//results
export const RESULTS_SHOW = 'RESULTS_SHOW';
export const RESULTS_TOGGLE_COUNTRY = 'RESULTS_TOGGLE_COUNTRY';
export const CLOSE = 'CLOSE';

//update
export const UPDATE_CHANGE_STATE = 'UPDATE_CHANGE_STATE';
export const UPDATE_UP_DOWNLOAD_PROGRESS = 'UPDATE_UP_DOWNLOAD_PROGRESS';
export const UPDATE_CLOSE = 'UPDATE_CLOSE';
